version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes: #allows getting the updates made to the project into the docker image in real time. It means that when a
             # file is updated in the project, it will automatically be updated in docker without restarting the
             # container
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
